name: Publish to npm

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Make CLI executable
        run: chmod +x bin/cli.js

      - name: Determine NPM tag
        id: npm-tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          if [[ "$VERSION" == *"dev"* ]]; then TAG="dev";
          elif [[ "$VERSION" == *"beta"* ]]; then TAG="latest";
          elif [[ "$VERSION" == *"alpha"* ]]; then TAG="latest";
          elif [[ "$VERSION" == *"rc"* ]]; then TAG="next";
          else TAG="latest"; fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        run: npm publish --tag "${{ steps.npm-tag.outputs.tag }}" --access public
